name: "Dotnet Test"
description: "Test a .NET project with optional coverage."

inputs:
  project-path:
    description: "The path to the .NET project or solution to test."
    required: false
  configuration:
    description: "The build configuration (e.g., Debug or Release)."
    required: false
    default: "Debug"
  coverage:
    description: "Whether to collect code coverage (true/false)."
    required: false
    default: "false"
  coverage-output:
    description: "The directory where code coverage results will be saved (if coverage is enabled)."
    required: false
    default: "TestResults/"
  continue-on-error:
    description: "Continue workflow if tests fail"
    required: false
    default: "true"

outputs:
  coverage-result:
    description: "The result of the code coverage execution (if enabled)."
    value: ${{ steps.run-tests.outputs.coverage-result }}

runs:
  using: "composite"
  steps:
    - name: Run Tests with coverage
      if: ${{ inputs.coverage == 'true' }}
      continue-on-error: ${{ inputs.continue-on-error }} 
      run: dotnet test ${{ inputs.project-path && inputs.project-path || '' }} \
        --collect:"XPlat Code Coverage;Format=opencover" \
        --results-directory ${{ inputs.coverage-output }} \
        --configuration ${{ inputs.configuration }} 
      shell: bash

    - name: Set Coverage Result Output
      id: run-tests
      if: ${{ inputs.coverage == 'true' }}
      run: echo "coverage-result=$version" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Run Tests without coverage
      if: ${{ inputs.coverage != 'true' }}
      continue-on-error: ${{ inputs.continue-on-error }} 
      run: dotnet test ${{ inputs.project-path && inputs.project-path || '' }} \ 
        --configuration ${{ inputs.configuration }} 
      shell: bash